
const USER_ROLE = {
    ADMIN: 0,
    AGENCY: 1
}

const countries_option_value_list = ["KBL", "TIA"
, "ALG"
, "LUA"
, "BNS"
, "YRV"
, "MLB"
, "PRT"
, "SYD"
, "VNN"
, "BKU"
, "NSS"
, "MNA"
, "DHK"
, "BGN"
, "MSK"
, "BRS"
, "BLZ"
, "COT"
, "HML"
, "LPZ"
, "SAR"
, "GAB"
, "BRA"
, "PTA"
, "RCF"
, "RDJ"
, "SPL"
, "BSB"
, "SOF"
, "OUG"
, "RNG"
, "BUJ"
, "PIA"
, "PHP"
, "YDE"
, "CLG"
, "HLF"
, "MTL"
, "OTT"
, "QBC"
, "TRT"
, "VAC"
, "NDJ"
, "SNT"
, "BEJ"
, "CHE"
, "GUZ"
, "SHG"
, "SNY"
, "BGT"
, "BRZ"
, "KIN"
, "SNJ"
, "ABJ"
, "ZGB"
, "HAV"
, "CRC"
, "NCS"
, "PRG"
, "CPN"
, "DJI"
, "SDO"
, "GYQ"
, "QTO"
, "CRO"
, "SNS"
, "LND"
, "MBO"
, "ASM"
, "TAL"
, "MBA"
, "ADD"
, "SUV"
, "HLS"
, "PRS"
, "LIB"
, "BAN"
, "TBL"
, "BRL"
, "FRN"
, "MUN"
, "ACC"
, "ATH"
, "GTM"
, "CRY"
, "GEO"
, "PTP"
, "TGG"
, "HNK"
, "BDP"
, "RKJ"
, "MDR"
, "HYD"
, "CLC"
, "BMB"
, "NWD"
, "JAK"
, "SRB"
, "BGH"
, "ERB"
, "DBL"
, "TLV"
, "FLR"
, "MLN"
, "NPL"
, "RME"
, "KNG"
, "NHA"
, "KBO"
, "TKY"
, "JRS"
, "AMM"
, "ATA"
, "AST"
, "NRB"
, "PRI"
, "KWT"
, "BKK"
, "VNT"
, "RGA"
, "BRT"
, "MAS"
, "MRV"
, "VIL"
, "LXM"
, "SKO"
, "ANT"
, "LIL"
, "KLL"
, "BAM"
, "VLL"
, "MAJ"
, "NUK"
, "PTL"
, "CDJ"
, "GDL"
, "HER"
, "MTM"
, "MER"
, "MEX"
, "MTR"
, "NGL"
, "NVL"
, "TJT"
, "KOL"
, "CHS"
, "ULN"
, "POD"
, "CSB"
, "MAP"
, "WHK"
, "KDU"
, "AMS"
, "ACK"
, "MNG"
, "NMY"
, "ABU"
, "LGS"
, "BLF"
, "OSL"
, "MST"
, "ISL"
, "KRC"
, "KOR"
, "PNM"
, "PTM"
, "ASN"
, "LMA"
, "MNL"
, "KRK"
, "WRW"
, "LSB"
, "DOH"
, "BCH"
, "MOS"
, "VLA"
, "YEK"
, "KGL"
, "APA"
, "DHR"
, "JDD"
, "RID"
, "DKR"
, "BLG"
, "FTN"
, "SGP"
, "BTS"
, "LJU"
, "CPT"
, "DRB"
, "JHN"
, "SEO"
, "JBA"
, "MDD"
, "CLM"
, "KHT"
, "PRM"
, "STK"
, "BEN"
, "TAI"
, "DHB"
, "DRS"
, "BNK"
, "CHN"
, "DIL"
, "LOM"
, "PTS"
, "TNS"
, "ANK"
, "IST"
, "AKD"
, "KMP"
, "KEV"
, "ABD"
, "DUB"
, "MTV"
, "THT"
, "CRS"
, "HAN"
, "HCM"
, "LUS"
, "HRE"];
const countries_option_label_list = [
"AFGHANISTAN, KABUL",
"ALBANIA, TIRANA",
"ALGERIA, ALGIERS",
"ANGOLA, LUANDA",
"ARGENTINA, BUENOS AIRES",
"ARMENIA, YEREVAN",
"AUSTRALIA, MELBOURNE",
"AUSTRALIA, PERTH",
"AUSTRALIA, SYDNEY",
"AUSTRIA, VIENNA",
"AZERBAIJAN, BAKU",
"BAHAMAS, NASSAU",
"BAHRAIN, MANAMA",
"BANGLADESH, DHAKA",
"BARBADOS, BRIDGETOWN",
"BELARUS, MINSK",
"BELGIUM, BRUSSELS",
"BELIZE, BELMOPAN",
"BENIN, COTONOU",
"BERMUDA, HAMILTON",
"BOLIVIA, LA PAZ",
"BOSNIA-HERZEGOVINA, SARAJEVO",
"BOTSWANA, GABORONE",
"BRAZIL, BRASILIA",
"BRAZIL, PORTO ALEGRE",
"BRAZIL, RECIFE",
"BRAZIL, RIO DE JANEIRO",
"BRAZIL, SAO PAULO",
"BRUNEI, BANDAR SERI BEGAWAN",
"BULGARIA, SOFIA",
"BURKINA FASO, OUAGADOUGOU",
"BURMA, RANGOON",
"BURUNDI, BUJUMBURA",
"CABO VERDE, PRAIA",
"CAMBODIA, PHNOM PENH",
"CAMEROON, YAOUNDE",
"CANADA, CALGARY",
"CANADA, HALIFAX",
"CANADA, MONTREAL",
"CANADA, OTTAWA",
"CANADA, QUEBEC",
"CANADA, TORONTO",
"CANADA, VANCOUVER",
"CHAD, N`DJAMENA",
"CHILE, SANTIAGO",
"CHINA, BEIJING",
"CHINA, CHENGDU",
"CHINA, GUANGZHOU",
"CHINA, SHANGHAI",
"CHINA, SHENYANG",
"COLOMBIA, BOGOTA",
"CONGO, BRAZZAVILLE",
"CONGO, KINSHASA",
"COSTA RICA, SAN JOSE",
"COTE D`IVORIE, ABIDJAN",
"CROATIA, ZAGREB",
"CUBA, HAVANA",
"CURACAO, CURACAO",
"CYPRUS, NICOSIA",
"CZECH REPUBLIC, PRAGUE",
"DENMARK, COPENHAGEN",
"DJIBOUTI, DJIBOUTI",
"DOMINICAN REPUBLIC, SANTO DOMINGO",
"ECUADOR, GUAYAQUIL",
"ECUADOR, QUITO",
"EGYPT, CAIRO",
"EL SALVADOR, SAN SALVADOR",
"ENGLAND, LONDON",
"EQUATORIAL GUINEA, MALABO",
"ERITREA, ASMARA",
"ESTONIA, TALLINN",
"ESWATINI, MBABANE",
"ETHIOPIA, ADDIS ABABA",
"FIJI, SUVA",
"FINLAND, HELSINKI",
"FRANCE, PARIS",
"GABON, LIBREVILLE",
"GAMBIA, BANJUL",
"GEORGIA, TBILISI",
"GERMANY, BERLIN",
"GERMANY, FRANKFURT",
"GERMANY, MUNICH",
"GHANA, ACCRA",
"GREECE, ATHENS",
"GUATEMALA, GUATEMALA CITY",
"GUINEA, CONAKRY",
"GUYANA, GEORGETOWN",
"HAITI, PORT-AU-PRINCE",
"HONDURAS, TEGUCIGALPA",
"HONG KONG",
"HUNGARY, BUDAPEST",
"ICELAND, REYKJAVIK",
"INDIA, CHENNAI",
"INDIA, HYDERABAD",
"INDIA, KOLKATA",
"INDIA, MUMBAI",
"INDIA, NEW DELHI",
"INDONESIA, JAKARTA",
"INDONESIA, SURABAYA",
"IRAQ, BAGHDAD",
"IRAQ, ERBIL",
"IRELAND, DUBLIN",
"ISRAEL, TEL AVIV",
"ITALY, FLORENCE",
"ITALY, MILAN",
"ITALY, NAPLES",
"ITALY, ROME",
"JAMAICA, KINGSTON",
"JAPAN, NAHA",
"JAPAN, OSAKA/FUKUOKA",
"JAPAN, TOKYO/SAPPORO",
"JERUSALEM",
"JORDAN, AMMAN",
"KAZAKHSTAN, ALMATY",
"KAZAKHSTAN, ASTANA",
"KENYA, NAIROBI",
"KOSOVO, PRISTINA",
"KUWAIT, KUWAIT CITY",
"KYRGYZSTAN, BISHKEK",
"LAOS, VIENTIANE",
"LATVIA, RIGA",
"LEBANON, BEIRUT",
"LESOTHO, MASERU",
"LIBERIA, MONROVIA",
"LITHUANIA, VILNIUS",
"LUXEMBOURG, LUXEMBOURG",
"MACEDONIA, SKOPJE",
"MADAGASCAR, ANTANANARIVO",
"MALAWI, LILONGWE",
"MALAYSIA, KUALA LUMPUR",
"MALI, BAMAKO",
"MALTA, VALLETTA",
"MARSHALL ISLANDS, MAJURO",
"MAURITANIA, NOUAKCHOTT",
"MAURITIUS, PORT LOUIS",
"MEXICO, CIUDAD JUAREZ",
"MEXICO, GUADALAJARA",
"MEXICO, HERMOSILLO",
"MEXICO, MATAMOROS",
"MEXICO, MERIDA",
"MEXICO, MEXICO CITY",
"MEXICO, MONTERREY",
"MEXICO, NOGALES",
"MEXICO, NUEVO LAREDO",
"MEXICO, TIJUANA",
"MICRONESIA, KOLONIA",
"MOLDOVA, CHISINAU",
"MONGOLIA, ULAANBAATAR",
"MONTENEGRO, PODGORICA",
"MOROCCO, CASABLANCA",
"MOZAMBIQUE, MAPUTO",
"NAMIBIA, WINDHOEK",
"NEPAL, KATHMANDU",
"NETHERLANDS, AMSTERDAM",
"NEW ZEALAND, AUCKLAND",
"NICARAGUA, MANAGUA",
"NIGER, NIAMEY",
"NIGERIA, ABUJA",
"NIGERIA, LAGOS",
"NORTHERN IRELAND, BELFAST",
"NORWAY, OSLO",
"OMAN, MUSCAT",
"PAKISTAN, ISLAMABAD",
"PAKISTAN, KARACHI",
"PALAU, KOROR",
"PANAMA, PANAMA CITY",
"PAPUA NEW GUINEA, PORT MORESBY",
"PARAGUAY, ASUNCION",
"PERU, LIMA",
"PHILIPPINES, MANILA",
"POLAND, KRAKOW",
"POLAND, WARSAW",
"PORTUGAL, LISBON",
"QATAR, DOHA",
"ROMANIA, BUCHAREST",
"RUSSIA, MOSCOW",
"RUSSIA, VLADIVOSTOK",
"RUSSIA, YEKATERINBURG",
"RWANDA, KIGALI",
"SAMOA, APIA",
"SAUDI ARABIA, DHAHRAN",
"SAUDI ARABIA, JEDDAH",
"SAUDI ARABIA, RIYADH",
"SENEGAL, DAKAR",
"SERBIA, BELGRADE",
"SIERRA LEONE, FREETOWN",
"SINGAPORE, SINGAPORE",
"SLOVAKIA, BRATISLAVA",
"SLOVENIA, LJUBLJANA",
"SOUTH AFRICA, CAPE TOWN",
"SOUTH AFRICA, DURBAN",
"SOUTH AFRICA, JOHANNESBURG",
"SOUTH KOREA, SEOUL",
"SOUTH SUDAN, JUBA",
"SPAIN, MADRID",
"SRI LANKA, COLOMBO",
"SUDAN, KHARTOUM",
"SURINAME, PARAMARIBO",
"SWEDEN, STOCKHOLM",
"SWITZERLAND, BERN",
"TAIWAN, TAIPEI",
"TAJIKISTAN, DUSHANBE",
"TANZANIA, DAR ES SALAAM",
"THAILAND, BANGKOK",
"THAILAND, CHIANG MAI",
"TIMOR LESTE, DILI",
"TOGO, LOME",
"TRINIDAD, PORT OF SPAIN",
"TUNISIA, TUNIS",
"TURKEY, ANKARA",
"TURKEY, ISTANBUL",
"TURKMENISTAN, ASHGABAT",
"UGANDA, KAMPALA",
"UKRAINE, KYIV",
"UNITED ARAB EMIRATES, ABU DHABI",
"UNITED ARAB EMIRATES, DUBAI",
"URUGUAY, MONTEVIDEO",
"UZBEKISTAN, TASHKENT",
"VENEZUELA, CARACAS",
"VIETNAM, HANOI",
"VIETNAM, HO CHI MINH CITY",
"ZAMBIA, LUSAKA",
"ZIMBABWE, HARARE",
]
module.exports = {
    countries_option_value_list,
    countries_option_label_list,
    USER_ROLE
}